# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Required in order to use custom build configurations
project 'Orang3', 'Debug-dev' => :debug, 'Debug-uat' => :debug, 'Debug-prod' => :debug

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Orang3' do
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Google-Maps-iOS-Utils', '4.2.2'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )  

  ENVFILES = {
    'Debug-dev' => '$(PODS_ROOT)/../../.env.dev',
    'Debug-uat' => '$(PODS_ROOT)/../../.env.uat',
    'Debug-prod' => '$(PODS_ROOT)/../../.env.prod',
    'Release-dev' => '$(PODS_ROOT)/../../.env.dev',
    'Release-uat' => '$(PODS_ROOT)/../../.env.uat',
    'Release' => '$(PODS_ROOT)/../../.env.prod',
  }

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        # config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        # config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end
  end
end